import { BusinessProfile } from '@/types';

export const SAMPLE_LOCKSMITH: BusinessProfile = {
  id: 'sample-locksmith',
  name: 'Apex 24/7 Locksmith & Security',
  industry: 'locksmith',
  placeId: 'ChIJV4l7s18b5TkR5ZqjK9eO1bA',
  address: '742 Evergreen Terrace',
  city: 'Chicago',
  state: 'IL',
  postalCode: '60601',
  phone: '+1 (312) 555-0199',
  website: 'https://apexlocksmith-chicago.com',
  rating: 4.8,
  totalReviews: 342,
  healthScore: 88,
  grade: 'A',
  googleMapsUrl: 'https://maps.google.com/?cid=1084291823901928371',
  claimedStatus: 'Claimed & Verified',
  coordinates: { lat: 41.8781, lng: -87.6298 },
  openingHours: 'Open 24 Hours, 7 Days a Week',
  establishedYear: 2017,
  primaryCategory: 'Locksmith',
  primaryCategoryId: 'gcid:locksmith',
  secondaryCategories: [
    { id: 'sec-1', name: 'Emergency Locksmith Service', searchVolume: 14200, rankingDifficulty: 'High', isCurrentlyUsed: true, matchScore: 98 },
    { id: 'sec-2', name: 'Key Duplication Service', searchVolume: 8100, rankingDifficulty: 'Low', isCurrentlyUsed: true, matchScore: 92 },
    { id: 'sec-3', name: 'Safe & Vault Shop', searchVolume: 3400, rankingDifficulty: 'Medium', isCurrentlyUsed: false, matchScore: 84 },
    { id: 'sec-4', name: 'Security System Supplier', searchVolume: 12500, rankingDifficulty: 'High', isCurrentlyUsed: false, matchScore: 79 },
    { id: 'sec-5', name: 'Door Supplier', searchVolume: 4200, rankingDifficulty: 'Medium', isCurrentlyUsed: false, matchScore: 71 },
  ],
  metrics: {
    napConsistency: {
      score: 95,
      status: 'Optimal',
      details: 'Business name, phone (+1 312 555-0199), and suite address 100% matched across Google, Yelp, and Apple Maps.',
    },
    categoriesHealth: {
      score: 84,
      status: 'Missing Secondaries',
      details: 'Primary category Locksmith is properly set. Missing high-intent secondaries: "Safe & Vault Shop" and "Security System Supplier".',
    },
    reviewsHealth: {
      score: 92,
      status: 'Strong',
      details: '342 reviews with 4.8 star average. 91% response rate to customer feedback with average reply speed of 4.2 hours.',
    },
    photosHealth: {
      score: 78,
      count: 64,
      competitorAvg: 110,
      freshnessDays: 14,
      status: 'Fair',
      details: '64 photos uploaded. Competitors in Downtown Chicago average 110 photos. Last uploaded 14 days ago.',
    },
    postsHealth: {
      score: 90,
      frequencyPerMonth: 4,
      lastPostDaysAgo: 3,
      status: 'Active',
      details: 'Averaging 1 post per week with clear CTA buttons. Last post published 3 days ago.',
    },
  },
  geoGrid: {
    targetKeyword: 'emergency locksmith near me',
    radiusKm: 5,
    gridSize: '5x5',
    agr: 2.8,
    amr: 2.1,
    solv: 76.0,
    points: [
      { id: 'p-1', row: 0, col: 0, rank: 4, lat: 41.91, lng: -87.67, distanceKm: 4.8, competitorAbove: 'Windy City Locks' },
      { id: 'p-2', row: 0, col: 1, rank: 3, lat: 41.91, lng: -87.65, distanceKm: 3.9 },
      { id: 'p-3', row: 0, col: 2, rank: 2, lat: 41.91, lng: -87.63, distanceKm: 3.6 },
      { id: 'p-4', row: 0, col: 3, rank: 3, lat: 41.91, lng: -87.61, distanceKm: 3.9 },
      { id: 'p-5', row: 0, col: 4, rank: 6, lat: 41.91, lng: -87.59, distanceKm: 4.9, competitorAbove: 'Lakefront Security' },
      { id: 'p-6', row: 1, col: 0, rank: 3, lat: 41.89, lng: -87.67, distanceKm: 3.4 },
      { id: 'p-7', row: 1, col: 1, rank: 2, lat: 41.89, lng: -87.65, distanceKm: 2.1 },
      { id: 'p-8', row: 1, col: 2, rank: 1, lat: 41.89, lng: -87.63, distanceKm: 1.4 },
      { id: 'p-9', row: 1, col: 3, rank: 2, lat: 41.89, lng: -87.61, distanceKm: 2.1 },
      { id: 'p-10', row: 1, col: 4, rank: 4, lat: 41.89, lng: -87.59, distanceKm: 3.5 },
      { id: 'p-11', row: 2, col: 0, rank: 2, lat: 41.878, lng: -87.67, distanceKm: 3.3 },
      { id: 'p-12', row: 2, col: 1, rank: 1, lat: 41.878, lng: -87.65, distanceKm: 1.6 },
      { id: 'p-13', row: 2, col: 2, rank: 1, lat: 41.878, lng: -87.6298, distanceKm: 0.0 }, // Center
      { id: 'p-14', row: 2, col: 3, rank: 1, lat: 41.878, lng: -87.61, distanceKm: 1.6 },
      { id: 'p-15', row: 2, col: 4, rank: 3, lat: 41.878, lng: -87.59, distanceKm: 3.3 },
      { id: 'p-16', row: 3, col: 0, rank: 4, lat: 41.86, lng: -87.67, distanceKm: 3.8 },
      { id: 'p-17', row: 3, col: 1, rank: 2, lat: 41.86, lng: -87.65, distanceKm: 2.6 },
      { id: 'p-18', row: 3, col: 2, rank: 2, lat: 41.86, lng: -87.63, distanceKm: 2.0 },
      { id: 'p-19', row: 3, col: 3, rank: 2, lat: 41.86, lng: -87.61, distanceKm: 2.5 },
      { id: 'p-20', row: 3, col: 4, rank: 5, lat: 41.86, lng: -87.59, distanceKm: 3.7 },
      { id: 'p-21', row: 4, col: 0, rank: 7, lat: 41.84, lng: -87.67, distanceKm: 5.2, competitorAbove: 'South Side Keys' },
      { id: 'p-22', row: 4, col: 1, rank: 4, lat: 41.84, lng: -87.65, distanceKm: 4.4 },
      { id: 'p-23', row: 4, col: 2, rank: 3, lat: 41.84, lng: -87.63, distanceKm: 4.2 },
      { id: 'p-24', row: 4, col: 3, rank: 4, lat: 41.84, lng: -87.61, distanceKm: 4.4 },
      { id: 'p-25', row: 4, col: 4, rank: 8, lat: 41.84, lng: -87.59, distanceKm: 5.3, competitorAbove: 'Metro Locksmiths' },
    ],
  },
  reviewsData: {
    averageRating: 4.8,
    totalReviews: 342,
    starDistribution: { 5: 290, 4: 38, 3: 8, 2: 3, 1: 3 },
    sentimentSplit: { positive: 89, neutral: 8, negative: 3 },
    responseRate: 91,
    averageResponseTimeHours: 4.2,
    topKeywords: [
      { keyword: 'quick response', count: 114, sentiment: 'positive' },
      { keyword: 'car lockout', count: 87, sentiment: 'positive' },
      { keyword: 'reasonable price', count: 72, sentiment: 'positive' },
      { keyword: 'professional tech', count: 65, sentiment: 'positive' },
      { keyword: 'late arrival', count: 5, sentiment: 'negative' },
      { keyword: 'rekey service', count: 48, sentiment: 'positive' },
    ],
    reviews: [
      {
        id: 'rev-1',
        authorName: 'Marcus Vance',
        rating: 5,
        date: '2 days ago',
        content: 'Locked myself out of my apartment at midnight in the freezing rain. Apex arrived in 18 minutes, opened the smart deadlock without a scratch, and gave upfront pricing. Absolute lifesaver!',
        sentiment: 'positive',
        hasOwnerReply: true,
        ownerReply: 'Thank you Marcus! We know emergency lockouts are stressful, especially late at night. Glad our technician could get you safely inside quickly!',
        keywords: ['emergency', 'quick response', 'lockout', 'pricing'],
      },
      {
        id: 'rev-2',
        authorName: 'Sarah Jenkins',
        rating: 5,
        date: '1 week ago',
        content: 'Used Apex to rekey 4 commercial deadbolts at our retail boutique downtown. Flawless work, clean, courteous, and provided master keys right on the spot.',
        sentiment: 'positive',
        hasOwnerReply: true,
        ownerReply: 'We appreciate your business Sarah! Happy we could assist with securing your downtown boutique.',
        keywords: ['rekey service', 'commercial', 'master key'],
      },
      {
        id: 'rev-3',
        authorName: 'David K.',
        rating: 3,
        date: '3 weeks ago',
        content: 'Good locksmith work on rekeying my front door, but the technician arrived 30 minutes past the estimated 45-minute window due to highway traffic.',
        sentiment: 'neutral',
        hasOwnerReply: false,
        keywords: ['late arrival', 'rekey service', 'traffic'],
      },
      {
        id: 'rev-4',
        authorName: 'Elena Rostova',
        rating: 5,
        date: '1 month ago',
        content: 'Duplicate transponder keys for my 2021 Honda Civic were half the price of the dealership. Programmed in under 15 minutes!',
        sentiment: 'positive',
        hasOwnerReply: true,
        ownerReply: 'Dealership transponder programming is notoriously overpriced! Happy we could save you money, Elena.',
        keywords: ['car lockout', 'reasonable price', 'transponder'],
      },
    ],
  },
  competitors: [
    {
      id: 'comp-1',
      name: 'Apex 24/7 Locksmith (You)',
      isTarget: true,
      rating: 4.8,
      reviewsCount: 342,
      primaryCategory: 'Locksmith',
      secondaryCategoriesCount: 2,
      photosCount: 64,
      postsPerMonth: 4,
      domainAuthority: 34,
      citationsScore: 92,
      listingAgeYears: 7,
      responseRate: 91,
      gapSummary: 'Leading in response rate; needs more photos and 2 secondary categories to dominate outer ring.',
    },
    {
      id: 'comp-2',
      name: 'Windy City Master Locks',
      isTarget: false,
      rating: 4.9,
      reviewsCount: 489,
      primaryCategory: 'Locksmith',
      secondaryCategoriesCount: 5,
      photosCount: 142,
      postsPerMonth: 6,
      domainAuthority: 42,
      citationsScore: 96,
      listingAgeYears: 11,
      responseRate: 78,
      gapSummary: 'Has +147 more reviews and 5 active secondary categories giving them rank #1 in North Loop.',
    },
    {
      id: 'comp-3',
      name: 'Chicago 24/7 Key Pros',
      isTarget: false,
      rating: 4.6,
      reviewsCount: 275,
      primaryCategory: 'Emergency Locksmith Service',
      secondaryCategoriesCount: 3,
      photosCount: 88,
      postsPerMonth: 1,
      domainAuthority: 28,
      citationsScore: 84,
      listingAgeYears: 5,
      responseRate: 64,
      gapSummary: 'Primary category targeting emergency service directly; weaker review velocity and DA.',
    },
    {
      id: 'comp-4',
      name: 'Metro Lock & Safe Co.',
      isTarget: false,
      rating: 4.7,
      reviewsCount: 310,
      primaryCategory: 'Safe & Vault Shop',
      secondaryCategoriesCount: 4,
      photosCount: 105,
      postsPerMonth: 2,
      domainAuthority: 31,
      citationsScore: 88,
      listingAgeYears: 9,
      responseRate: 81,
      gapSummary: 'Monopolizes safe opening and vault keywords; weak Google Post updates.',
    },
  ],
  actionChecklist: [
    {
      id: 'act-1',
      title: 'Add "Safe & Vault Shop" as Secondary Category',
      category: 'Categories',
      priority: 'Critical',
      effort: 'Quick Win',
      completed: false,
      description: 'Your top competitor Windy City Master Locks captures 3,400 monthly searches by listing Safe & Vault Shop in their GBP profile.',
      howToFix: [
        'Open Google Business Profile dashboard.',
        'Navigate to Edit Profile > Business category.',
        'Click Add another category and select "Safe & Vault Shop".',
        'Save changes. Verification is immediate for secondary categories.',
      ],
      expectedImpact: '+18% visibility in commercial and residential safe opening search queries.',
    },
    {
      id: 'act-2',
      title: 'Upload 30 High-Resolution Geo-Tagged Photos',
      category: 'Photos',
      priority: 'High',
      effort: 'Moderate',
      completed: false,
      description: 'Competitors average 110 photos while Apex has 64. Profiles with 100+ photos receive 520% more calls according to Google research.',
      howToFix: [
        'Photograph service vans, mobile workshop interior, modern key cutting equipment, and team in uniform.',
        'Ensure real customer job photos (with consent). Avoid stock photography.',
        'Upload 5 photos every week to establish an active freshness signal.',
      ],
      expectedImpact: 'Higher engagement and trust badge ranking boost across Google Maps mobile app.',
    },
    {
      id: 'act-3',
      title: 'Reply to 3 Pending Neutral/Negative Reviews',
      category: 'Reviews',
      priority: 'High',
      effort: 'Quick Win',
      completed: false,
      description: 'Review #3 from David K. regarding 30-minute delay has remained unreplied for 21 days.',
      howToFix: [
        'Use our 1-Click AI Reply generator below with "Empathetic Professional" tone.',
        'Acknowledge the Chicago traffic delay, explain your GPS dispatch tracking system, and offer a customer satisfaction follow-up.',
      ],
      expectedImpact: 'Boosts review response rate from 91% to 94% and neutralizes negative conversion drag.',
    },
    {
      id: 'act-4',
      title: 'Standardize Suite Number Across Bing & Apple Business',
      category: 'NAP',
      priority: 'Medium',
      effort: 'Moderate',
      completed: true,
      description: 'Discrepancy detected: Apple Maps listed "Ste 200" while Google Maps listed "Suite 200".',
      howToFix: [
        'Updated Apple Business Connect listing to match Google Profile format.',
      ],
      expectedImpact: 'Prevents algorithmic confusion in local citation confidence scores.',
    },
    {
      id: 'act-5',
      title: 'Publish Weekly "Google Offer Post" with 10% Discount Code',
      category: 'Posts',
      priority: 'Medium',
      effort: 'Quick Win',
      completed: false,
      description: 'Google Posts expire after 7 days for visibility feeds. Offer posts drive high click-to-call intent on mobile searches.',
      howToFix: [
        'Generate an Offer Post using our AI Post Generator modal.',
        'Include coupon code "APEXLOCK10" and Call-to-Action button "Call Now".',
      ],
      expectedImpact: 'Generates direct call conversions directly from the Knowledge Panel snippet.',
    },
  ],
  recentPosts: [
    {
      id: 'post-1',
      type: 'OFFER',
      title: '15% Off Smart Deadbolt Installation This Week',
      content: 'Upgrade your home security with keypad smart deadbolts! Get 15% off installation labor throughout Chicago through the end of the month. Call now for same-day dispatch.',
      ctaType: 'CALL_NOW',
      ctaUrl: 'tel:+13125550199',
      couponCode: 'SMART15',
      startDate: '2026-09-01',
      endDate: '2026-09-30',
      dateCreated: '3 days ago',
      status: 'PUBLISHED',
    },
  ],
};

export const SAMPLE_DENTAL: BusinessProfile = {
  id: 'sample-dental',
  name: 'BrightSmile Dental Studio',
  industry: 'dental',
  placeId: 'ChIJDentalStudioPlaceId991',
  address: '450 Sutter St #1400',
  city: 'San Francisco',
  state: 'CA',
  postalCode: '94108',
  phone: '+1 (415) 555-8392',
  website: 'https://brightsmiledental-sf.com',
  rating: 4.9,
  totalReviews: 512,
  healthScore: 94,
  grade: 'A+',
  googleMapsUrl: 'https://maps.google.com/?cid=918237198273918273',
  claimedStatus: 'Claimed & Verified',
  coordinates: { lat: 37.7891, lng: -122.4075 },
  openingHours: 'Mon - Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 2:00 PM',
  establishedYear: 2014,
  primaryCategory: 'Dentist',
  primaryCategoryId: 'gcid:dentist',
  secondaryCategories: [
    { id: 'sec-d1', name: 'Cosmetic Dentist', searchVolume: 18500, rankingDifficulty: 'High', isCurrentlyUsed: true, matchScore: 99 },
    { id: 'sec-d2', name: 'Teeth Whitening Service', searchVolume: 9200, rankingDifficulty: 'Medium', isCurrentlyUsed: true, matchScore: 94 },
    { id: 'sec-d3', name: 'Orthodontist', searchVolume: 16100, rankingDifficulty: 'High', isCurrentlyUsed: true, matchScore: 91 },
    { id: 'sec-d4', name: 'Dental Implants Periodontist', searchVolume: 11300, rankingDifficulty: 'High', isCurrentlyUsed: false, matchScore: 88 },
    { id: 'sec-d5', name: 'Emergency Dental Service', searchVolume: 14000, rankingDifficulty: 'High', isCurrentlyUsed: false, matchScore: 85 },
  ],
  metrics: {
    napConsistency: {
      score: 98,
      status: 'Optimal',
      details: 'Strict NAP consistency confirmed across 45 primary medical and local directories.',
    },
    categoriesHealth: {
      score: 91,
      status: 'Optimal',
      details: 'Cosmetic Dentist and Teeth Whitening active. Could add Dental Implants Periodontist for surgical intent.',
    },
    reviewsHealth: {
      score: 96,
      status: 'Strong',
      details: '512 reviews, 4.9 stars. 96% owner response rate within 2 hours. Exceptional patient praise.',
    },
    photosHealth: {
      score: 92,
      count: 185,
      competitorAvg: 120,
      freshnessDays: 5,
      status: 'Great',
      details: '185 high quality clinic, 3D scan, staff, and before/after smile transformation photos.',
    },
    postsHealth: {
      score: 86,
      frequencyPerMonth: 3,
      lastPostDaysAgo: 6,
      status: 'Active',
      details: 'Educational dental tips and patient spotlight posts published bi-weekly.',
    },
  },
  geoGrid: {
    targetKeyword: 'cosmetic dentist san francisco',
    radiusKm: 3,
    gridSize: '5x5',
    agr: 1.6,
    amr: 1.4,
    solv: 88.0,
    points: [
      { id: 'pd-1', row: 0, col: 0, rank: 2, lat: 37.80, lng: -122.42, distanceKm: 2.8 },
      { id: 'pd-2', row: 0, col: 1, rank: 2, lat: 37.80, lng: -122.41, distanceKm: 2.3 },
      { id: 'pd-3', row: 0, col: 2, rank: 1, lat: 37.80, lng: -122.40, distanceKm: 2.2 },
      { id: 'pd-4', row: 0, col: 3, rank: 2, lat: 37.80, lng: -122.39, distanceKm: 2.4 },
      { id: 'pd-5', row: 0, col: 4, rank: 3, lat: 37.80, lng: -122.38, distanceKm: 3.1 },
      { id: 'pd-6', row: 1, col: 0, rank: 2, lat: 37.79, lng: -122.42, distanceKm: 1.9 },
      { id: 'pd-7', row: 1, col: 1, rank: 1, lat: 37.79, lng: -122.41, distanceKm: 1.1 },
      { id: 'pd-8', row: 1, col: 2, rank: 1, lat: 37.79, lng: -122.40, distanceKm: 0.9 },
      { id: 'pd-9', row: 1, col: 3, rank: 1, lat: 37.79, lng: -122.39, distanceKm: 1.2 },
      { id: 'pd-10', row: 1, col: 4, rank: 2, lat: 37.79, lng: -122.38, distanceKm: 2.1 },
      { id: 'pd-11', row: 2, col: 0, rank: 1, lat: 37.789, lng: -122.42, distanceKm: 1.7 },
      { id: 'pd-12', row: 2, col: 1, rank: 1, lat: 37.789, lng: -122.41, distanceKm: 0.8 },
      { id: 'pd-13', row: 2, col: 2, rank: 1, lat: 37.789, lng: -122.4075, distanceKm: 0.0 }, // Center
      { id: 'pd-14', row: 2, col: 3, rank: 1, lat: 37.789, lng: -122.39, distanceKm: 0.9 },
      { id: 'pd-15', row: 2, col: 4, rank: 2, lat: 37.789, lng: -122.38, distanceKm: 1.8 },
      { id: 'pd-16', row: 3, col: 0, rank: 2, lat: 37.78, lng: -122.42, distanceKm: 2.1 },
      { id: 'pd-17', row: 3, col: 1, rank: 1, lat: 37.78, lng: -122.41, distanceKm: 1.4 },
      { id: 'pd-18', row: 3, col: 2, rank: 1, lat: 37.78, lng: -122.40, distanceKm: 1.1 },
      { id: 'pd-19', row: 3, col: 3, rank: 2, lat: 37.78, lng: -122.39, distanceKm: 1.5 },
      { id: 'pd-20', row: 3, col: 4, rank: 3, lat: 37.78, lng: -122.38, distanceKm: 2.3 },
      { id: 'pd-21', row: 4, col: 0, rank: 3, lat: 37.77, lng: -122.42, distanceKm: 3.2 },
      { id: 'pd-22', row: 4, col: 1, rank: 2, lat: 37.77, lng: -122.41, distanceKm: 2.6 },
      { id: 'pd-23', row: 4, col: 2, rank: 2, lat: 37.77, lng: -122.40, distanceKm: 2.4 },
      { id: 'pd-24', row: 4, col: 3, rank: 3, lat: 37.77, lng: -122.39, distanceKm: 2.7 },
      { id: 'pd-25', row: 4, col: 4, rank: 4, lat: 37.77, lng: -122.38, distanceKm: 3.5 },
    ],
  },
  reviewsData: {
    averageRating: 4.9,
    totalReviews: 512,
    starDistribution: { 5: 480, 4: 26, 3: 4, 2: 1, 1: 1 },
    sentimentSplit: { positive: 96, neutral: 3, negative: 1 },
    responseRate: 96,
    averageResponseTimeHours: 1.8,
    topKeywords: [
      { keyword: 'gentle cleaning', count: 180, sentiment: 'positive' },
      { keyword: 'invisalign results', count: 145, sentiment: 'positive' },
      { keyword: 'friendly staff', count: 210, sentiment: 'positive' },
      { keyword: 'modern clinic', count: 98, sentiment: 'positive' },
      { keyword: 'insurance billing', count: 12, sentiment: 'neutral' },
    ],
    reviews: [
      {
        id: 'rev-d1',
        authorName: 'Jessica Wu',
        rating: 5,
        date: '3 days ago',
        content: 'Dr. Taylor completely transformed my smile with porcelain veneers! Zero pain during procedures and their 3D scanner preview was spot on.',
        sentiment: 'positive',
        hasOwnerReply: true,
        ownerReply: 'Thank you Jessica! Watching our patients smile with newfound confidence is why we love what we do.',
        keywords: ['veneers', 'zero pain', '3D scanner'],
      },
    ],
  },
  competitors: [
    {
      id: 'comp-d1',
      name: 'BrightSmile Dental (You)',
      isTarget: true,
      rating: 4.9,
      reviewsCount: 512,
      primaryCategory: 'Dentist',
      secondaryCategoriesCount: 3,
      photosCount: 185,
      postsPerMonth: 3,
      domainAuthority: 48,
      citationsScore: 98,
      listingAgeYears: 10,
      responseRate: 96,
      gapSummary: 'Dominant local presence in Downtown SF; market leader in review volume and positive sentiment.',
    },
    {
      id: 'comp-d2',
      name: 'Union Square Aesthetics Dentistry',
      isTarget: false,
      rating: 4.8,
      reviewsCount: 390,
      primaryCategory: 'Cosmetic Dentist',
      secondaryCategoriesCount: 4,
      photosCount: 160,
      postsPerMonth: 4,
      domainAuthority: 44,
      citationsScore: 94,
      listingAgeYears: 8,
      responseRate: 90,
      gapSummary: 'Strong cosmetic category ranking; ranks closely behind in Nob Hill.',
    },
    {
      id: 'comp-d3',
      name: 'Pacific Heights Dental Care',
      isTarget: false,
      rating: 4.7,
      reviewsCount: 280,
      primaryCategory: 'Dentist',
      secondaryCategoriesCount: 2,
      photosCount: 95,
      postsPerMonth: 1,
      domainAuthority: 39,
      citationsScore: 89,
      listingAgeYears: 14,
      responseRate: 72,
      gapSummary: 'Established patient base but lagging on photo updates and review response velocity.',
    },
    {
      id: 'comp-d4',
      name: 'Bay Area Orthodontics & Implants',
      isTarget: false,
      rating: 4.6,
      reviewsCount: 215,
      primaryCategory: 'Orthodontist',
      secondaryCategoriesCount: 5,
      photosCount: 110,
      postsPerMonth: 2,
      domainAuthority: 36,
      citationsScore: 86,
      listingAgeYears: 6,
      responseRate: 85,
      gapSummary: 'Ranks high for braces and Invisalign but low volume in general cleaning.',
    },
  ],
  actionChecklist: [
    {
      id: 'act-d1',
      title: 'Add "Dental Implants Periodontist" Secondary Category',
      category: 'Categories',
      priority: 'High',
      effort: 'Quick Win',
      completed: false,
      description: 'Capture high-ticket surgical implant patients by activating this category in GBP.',
      howToFix: ['Access Google Business Profile manager', 'Select Add Secondary Category: Dental Implants Periodontist'],
      expectedImpact: '+25% discovery in high-value implant consultations.',
    },
  ],
  recentPosts: [
    {
      id: 'post-d1',
      type: 'EVENT',
      title: 'Free Cosmetic Smile Consultation Day',
      content: 'Thinking about Invisalign or teeth whitening before wedding season? Book a complimentary 3D scan this Friday.',
      ctaType: 'BOOK',
      ctaUrl: 'https://brightsmiledental-sf.com/book',
      dateCreated: '6 days ago',
      status: 'PUBLISHED',
    },
  ],
};

export const SAMPLE_RESTAURANT: BusinessProfile = {
  id: 'sample-restaurant',
  name: 'Bella Vista Trattoria & Pizzeria',
  industry: 'restaurant',
  placeId: 'ChIJRestaurantBellaVista992',
  address: '128 Mulberry St',
  city: 'New York',
  state: 'NY',
  postalCode: '10013',
  phone: '+1 (212) 555-4921',
  website: 'https://bellavistanyc.com',
  rating: 4.7,
  totalReviews: 894,
  healthScore: 82,
  grade: 'B+',
  googleMapsUrl: 'https://maps.google.com/?cid=120938102938102938',
  claimedStatus: 'Claimed & Verified',
  coordinates: { lat: 40.7185, lng: -73.9984 },
  openingHours: 'Mon - Sun: 11:30 AM - 11:00 PM',
  establishedYear: 2011,
  primaryCategory: 'Italian Restaurant',
  primaryCategoryId: 'gcid:italian_restaurant',
  secondaryCategories: [
    { id: 'sec-r1', name: 'Pizza Restaurant', searchVolume: 45000, rankingDifficulty: 'High', isCurrentlyUsed: true, matchScore: 98 },
    { id: 'sec-r2', name: 'Bar & Grill', searchVolume: 22000, rankingDifficulty: 'Medium', isCurrentlyUsed: false, matchScore: 82 },
    { id: 'sec-r3', name: 'Catering Food and Drink Supplier', searchVolume: 8400, rankingDifficulty: 'Medium', isCurrentlyUsed: false, matchScore: 78 },
    { id: 'sec-r4', name: 'Pasta Shop', searchVolume: 6100, rankingDifficulty: 'Low', isCurrentlyUsed: true, matchScore: 88 },
  ],
  metrics: {
    napConsistency: {
      score: 90,
      status: 'Optimal',
      details: 'Name and menu links aligned across Google Maps, OpenTable, Yelp, and Resy.',
    },
    categoriesHealth: {
      score: 75,
      status: 'Missing Secondaries',
      details: 'Missing "Catering Food and Drink Supplier" and "Wine Bar" categories.',
    },
    reviewsHealth: {
      score: 84,
      status: 'Needs Attention',
      details: '894 reviews. Response rate is only 58%. Over 120 customer reviews have no owner response.',
    },
    photosHealth: {
      score: 95,
      count: 420,
      competitorAvg: 310,
      freshnessDays: 1,
      status: 'Great',
      details: '420 customer and owner food photos. Updated daily by visiting diners.',
    },
    postsHealth: {
      score: 65,
      frequencyPerMonth: 1,
      lastPostDaysAgo: 24,
      status: 'Irregular',
      details: 'Only 1 post in the last month. Specials and seasonal chef menus are not actively shared on GBP.',
    },
  },
  geoGrid: {
    targetKeyword: 'best authentic pasta little italy',
    radiusKm: 2,
    gridSize: '5x5',
    agr: 3.2,
    amr: 2.8,
    solv: 64.0,
    points: [
      { id: 'pr-1', row: 0, col: 0, rank: 5, lat: 40.725, lng: -74.01, distanceKm: 1.8 },
      { id: 'pr-2', row: 0, col: 1, rank: 4, lat: 40.725, lng: -74.00, distanceKm: 1.4 },
      { id: 'pr-3', row: 0, col: 2, rank: 3, lat: 40.725, lng: -73.99, distanceKm: 1.3 },
      { id: 'pr-4', row: 0, col: 3, rank: 4, lat: 40.725, lng: -73.98, distanceKm: 1.6 },
      { id: 'pr-5', row: 0, col: 4, rank: 6, lat: 40.725, lng: -73.97, distanceKm: 2.2 },
      { id: 'pr-6', row: 1, col: 0, rank: 4, lat: 40.721, lng: -74.01, distanceKm: 1.3 },
      { id: 'pr-7', row: 1, col: 1, rank: 2, lat: 40.721, lng: -74.00, distanceKm: 0.8 },
      { id: 'pr-8', row: 1, col: 2, rank: 1, lat: 40.721, lng: -73.99, distanceKm: 0.6 },
      { id: 'pr-9', row: 1, col: 3, rank: 2, lat: 40.721, lng: -73.98, distanceKm: 1.1 },
      { id: 'pr-10', row: 1, col: 4, rank: 5, lat: 40.721, lng: -73.97, distanceKm: 1.9 },
      { id: 'pr-11', row: 2, col: 0, rank: 3, lat: 40.7185, lng: -74.01, distanceKm: 1.1 },
      { id: 'pr-12', row: 2, col: 1, rank: 1, lat: 40.7185, lng: -74.00, distanceKm: 0.4 },
      { id: 'pr-13', row: 2, col: 2, rank: 1, lat: 40.7185, lng: -73.9984, distanceKm: 0.0 }, // Center
      { id: 'pr-14', row: 2, col: 3, rank: 1, lat: 40.7185, lng: -73.99, distanceKm: 0.6 },
      { id: 'pr-15', row: 2, col: 4, rank: 4, lat: 40.7185, lng: -73.98, distanceKm: 1.4 },
      { id: 'pr-16', row: 3, col: 0, rank: 4, lat: 40.715, lng: -74.01, distanceKm: 1.4 },
      { id: 'pr-17', row: 3, col: 1, rank: 2, lat: 40.715, lng: -74.00, distanceKm: 0.8 },
      { id: 'pr-18', row: 3, col: 2, rank: 2, lat: 40.715, lng: -73.99, distanceKm: 0.9 },
      { id: 'pr-19', row: 3, col: 3, rank: 3, lat: 40.715, lng: -73.98, distanceKm: 1.3 },
      { id: 'pr-20', row: 3, col: 4, rank: 5, lat: 40.715, lng: -73.97, distanceKm: 2.1 },
      { id: 'pr-21', row: 4, col: 0, rank: 7, lat: 40.711, lng: -74.01, distanceKm: 2.1 },
      { id: 'pr-22', row: 4, col: 1, rank: 4, lat: 40.711, lng: -74.00, distanceKm: 1.6 },
      { id: 'pr-23', row: 4, col: 2, rank: 3, lat: 40.711, lng: -73.99, distanceKm: 1.5 },
      { id: 'pr-24', row: 4, col: 3, rank: 5, lat: 40.711, lng: -73.98, distanceKm: 1.8 },
      { id: 'pr-25', row: 4, col: 4, rank: 8, lat: 40.711, lng: -73.97, distanceKm: 2.6 },
    ],
  },
  reviewsData: {
    averageRating: 4.7,
    totalReviews: 894,
    starDistribution: { 5: 710, 4: 120, 3: 35, 2: 18, 1: 11 },
    sentimentSplit: { positive: 88, neutral: 8, negative: 4 },
    responseRate: 58,
    averageResponseTimeHours: 48,
    topKeywords: [
      { keyword: 'truffle pasta', count: 280, sentiment: 'positive' },
      { keyword: 'wood-fired pizza', count: 240, sentiment: 'positive' },
      { keyword: 'romantic ambiance', count: 175, sentiment: 'positive' },
      { keyword: 'long wait time', count: 32, sentiment: 'negative' },
      { keyword: 'tiramisu', count: 190, sentiment: 'positive' },
    ],
    reviews: [
      {
        id: 'rev-r1',
        authorName: 'Anthony Greco',
        rating: 5,
        date: 'Yesterday',
        content: 'Handmade cacio e pepe prepared inside the pecorino wheel right at the table! The crust on the Margherita pizza had the perfect char. Our new favorite in Little Italy.',
        sentiment: 'positive',
        hasOwnerReply: false,
        keywords: ['handmade pasta', 'margherita pizza', 'little italy'],
      },
    ],
  },
  competitors: [
    {
      id: 'comp-r1',
      name: 'Bella Vista Trattoria (You)',
      isTarget: true,
      rating: 4.7,
      reviewsCount: 894,
      primaryCategory: 'Italian Restaurant',
      secondaryCategoriesCount: 2,
      photosCount: 420,
      postsPerMonth: 1,
      domainAuthority: 41,
      citationsScore: 90,
      listingAgeYears: 15,
      responseRate: 58,
      gapSummary: 'Heavy photo volume and history; low review response rate and infrequent Google Posts.',
    },
    {
      id: 'comp-r2',
      name: 'Nonna Mia Osteria',
      isTarget: false,
      rating: 4.8,
      reviewsCount: 1140,
      primaryCategory: 'Italian Restaurant',
      secondaryCategoriesCount: 4,
      photosCount: 580,
      postsPerMonth: 5,
      domainAuthority: 46,
      citationsScore: 95,
      listingAgeYears: 18,
      responseRate: 92,
      gapSummary: 'Actively posts weekly chef specials; response rate over 90% gives them rank #1 in SoHo edge.',
    },
    {
      id: 'comp-r3',
      name: 'La Forchetta Romana',
      isTarget: false,
      rating: 4.6,
      reviewsCount: 620,
      primaryCategory: 'Pizza Restaurant',
      secondaryCategoriesCount: 3,
      photosCount: 290,
      postsPerMonth: 2,
      domainAuthority: 34,
      citationsScore: 87,
      listingAgeYears: 7,
      responseRate: 64,
      gapSummary: 'Lacks seating capacity; captures delivery pizza traffic.',
    },
    {
      id: 'comp-r4',
      name: 'San Gennaro Ristorante',
      isTarget: false,
      rating: 4.5,
      reviewsCount: 780,
      primaryCategory: 'Italian Restaurant',
      secondaryCategoriesCount: 2,
      photosCount: 350,
      postsPerMonth: 0,
      domainAuthority: 37,
      citationsScore: 89,
      listingAgeYears: 22,
      responseRate: 35,
      gapSummary: 'Tourist oriented; very low digital engagement.',
    },
  ],
  actionChecklist: [
    {
      id: 'act-r1',
      title: 'Automate Responses for 120+ Unreplied Reviews',
      category: 'Reviews',
      priority: 'Critical',
      effort: 'Moderate',
      completed: false,
      description: 'Your current response rate is 58%. Google rewards profiles that respond to >85% of reviews with higher local pack placement.',
      howToFix: ['Open our AI Review Assistant', 'Filter for Unreplied Reviews', 'Approve and submit batch replies in under 5 minutes'],
      expectedImpact: 'Raises response rate from 58% to 90%+, boosting consumer conversion and search rankings.',
    },
  ],
  recentPosts: [
    {
      id: 'post-r1',
      type: 'UPDATE',
      title: 'New Fall Black Truffle Menu Debut',
      content: 'Fresh black truffles arrived from Umbria! Savor our fresh pappardelle al tartufo all this weekend.',
      ctaType: 'ORDER',
      ctaUrl: 'https://bellavistanyc.com/menu',
      dateCreated: '24 days ago',
      status: 'PUBLISHED',
    },
  ],
};

export const SAMPLE_HVAC: BusinessProfile = {
  id: 'sample-hvac',
  name: 'Elite Climate HVAC Pros',
  industry: 'hvac',
  placeId: 'ChIJHVACProsHouston993',
  address: '1420 Westheimer Rd Suite B',
  city: 'Houston',
  state: 'TX',
  postalCode: '77006',
  phone: '+1 (713) 555-9042',
  website: 'https://eliteclimatehouston.com',
  rating: 4.9,
  totalReviews: 430,
  healthScore: 91,
  grade: 'A',
  googleMapsUrl: 'https://maps.google.com/?cid=9081230918230912',
  claimedStatus: 'Claimed & Verified',
  coordinates: { lat: 29.7431, lng: -95.3982 },
  openingHours: 'Mon - Sun: 7:00 AM - 9:00 PM (Emergency Dispatch 24/7)',
  establishedYear: 2016,
  primaryCategory: 'HVAC Contractor',
  primaryCategoryId: 'gcid:hvac_contractor',
  secondaryCategories: [
    { id: 'sec-h1', name: 'Air Conditioning Repair Service', searchVolume: 38000, rankingDifficulty: 'High', isCurrentlyUsed: true, matchScore: 99 },
    { id: 'sec-h2', name: 'Heating Contractor', searchVolume: 12400, rankingDifficulty: 'Medium', isCurrentlyUsed: true, matchScore: 93 },
    { id: 'sec-h3', name: 'Air Duct Cleaning Service', searchVolume: 15200, rankingDifficulty: 'Medium', isCurrentlyUsed: false, matchScore: 89 },
    { id: 'sec-h4', name: 'Furnace Repair Service', searchVolume: 9800, rankingDifficulty: 'Medium', isCurrentlyUsed: false, matchScore: 84 },
    { id: 'sec-h5', name: 'Insulation Contractor', searchVolume: 6200, rankingDifficulty: 'Low', isCurrentlyUsed: false, matchScore: 72 },
  ],
  metrics: {
    napConsistency: {
      score: 96,
      status: 'Optimal',
      details: 'Consistent Houston service area business definitions with verified contractor license displayed.',
    },
    categoriesHealth: {
      score: 88,
      status: 'Missing Secondaries',
      details: 'Air Conditioning Repair Service active. Missing Air Duct Cleaning Service which has 15,200 monthly searches.',
    },
    reviewsHealth: {
      score: 95,
      status: 'Strong',
      details: '430 reviews, 4.9 stars. Mentions of "same-day AC repair" and "honest diagnostic" prominent in review text.',
    },
    photosHealth: {
      score: 85,
      count: 92,
      competitorAvg: 80,
      freshnessDays: 8,
      status: 'Great',
      details: '92 photos showing neat AC condenser installations, technician ID badges, and clean duct inspections.',
    },
    postsHealth: {
      score: 92,
      frequencyPerMonth: 4,
      lastPostDaysAgo: 4,
      status: 'Active',
      details: 'Seasonal AC tune-up discounts and filter replacement reminders posted regularly.',
    },
  },
  geoGrid: {
    targetKeyword: 'emergency ac repair houston',
    radiusKm: 10,
    gridSize: '5x5',
    agr: 2.1,
    amr: 1.8,
    solv: 80.0,
    points: [
      { id: 'ph-1', row: 0, col: 0, rank: 3, lat: 29.82, lng: -95.48, distanceKm: 9.8 },
      { id: 'ph-2', row: 0, col: 1, rank: 2, lat: 29.82, lng: -95.44, distanceKm: 8.2 },
      { id: 'ph-3', row: 0, col: 2, rank: 2, lat: 29.82, lng: -95.398, distanceKm: 7.9 },
      { id: 'ph-4', row: 0, col: 3, rank: 3, lat: 29.82, lng: -95.35, distanceKm: 8.4 },
      { id: 'ph-5', row: 0, col: 4, rank: 5, lat: 29.82, lng: -95.31, distanceKm: 10.2 },
      { id: 'ph-6', row: 1, col: 0, rank: 2, lat: 29.78, lng: -95.48, distanceKm: 7.1 },
      { id: 'ph-7', row: 1, col: 1, rank: 2, lat: 29.78, lng: -95.44, distanceKm: 5.2 },
      { id: 'ph-8', row: 1, col: 2, rank: 1, lat: 29.78, lng: -95.398, distanceKm: 4.1 },
      { id: 'ph-9', row: 1, col: 3, rank: 2, lat: 29.78, lng: -95.35, distanceKm: 5.4 },
      { id: 'ph-10', row: 1, col: 4, rank: 4, lat: 29.78, lng: -95.31, distanceKm: 7.6 },
      { id: 'ph-11', row: 2, col: 0, rank: 2, lat: 29.7431, lng: -95.48, distanceKm: 6.8 },
      { id: 'ph-12', row: 2, col: 1, rank: 1, lat: 29.7431, lng: -95.44, distanceKm: 3.5 },
      { id: 'ph-13', row: 2, col: 2, rank: 1, lat: 29.7431, lng: -95.3982, distanceKm: 0.0 }, // Center
      { id: 'ph-14', row: 2, col: 3, rank: 1, lat: 29.7431, lng: -95.35, distanceKm: 4.2 },
      { id: 'ph-15', row: 2, col: 4, rank: 3, lat: 29.7431, lng: -95.31, distanceKm: 7.2 },
      { id: 'ph-16', row: 3, col: 0, rank: 3, lat: 29.70, lng: -95.48, distanceKm: 8.1 },
      { id: 'ph-17', row: 3, col: 1, rank: 2, lat: 29.70, lng: -95.44, distanceKm: 5.9 },
      { id: 'ph-18', row: 3, col: 2, rank: 1, lat: 29.70, lng: -95.398, distanceKm: 4.8 },
      { id: 'ph-19', row: 3, col: 3, rank: 2, lat: 29.70, lng: -95.35, distanceKm: 6.1 },
      { id: 'ph-20', row: 3, col: 4, rank: 4, lat: 29.70, lng: -95.31, distanceKm: 8.5 },
      { id: 'ph-21', row: 4, col: 0, rank: 6, lat: 29.66, lng: -95.48, distanceKm: 11.2 },
      { id: 'ph-22', row: 4, col: 1, rank: 3, lat: 29.66, lng: -95.44, distanceKm: 9.4 },
      { id: 'ph-23', row: 4, col: 2, rank: 2, lat: 29.66, lng: -95.398, distanceKm: 8.9 },
      { id: 'ph-24', row: 4, col: 3, rank: 4, lat: 29.66, lng: -95.35, distanceKm: 9.7 },
      { id: 'ph-25', row: 4, col: 4, rank: 7, lat: 29.66, lng: -95.31, distanceKm: 11.8 },
    ],
  },
  reviewsData: {
    averageRating: 4.9,
    totalReviews: 430,
    starDistribution: { 5: 395, 4: 28, 3: 4, 2: 2, 1: 1 },
    sentimentSplit: { positive: 94, neutral: 4, negative: 2 },
    responseRate: 94,
    averageResponseTimeHours: 3.5,
    topKeywords: [
      { keyword: 'same-day ac repair', count: 165, sentiment: 'positive' },
      { keyword: 'honest diagnosis', count: 120, sentiment: 'positive' },
      { keyword: 'new unit installation', count: 85, sentiment: 'positive' },
      { keyword: 'reasonable quote', count: 95, sentiment: 'positive' },
      { keyword: 'technician arrived on time', count: 110, sentiment: 'positive' },
    ],
    reviews: [
      {
        id: 'rev-h1',
        authorName: 'Carlos Morales',
        rating: 5,
        date: '4 days ago',
        content: 'Our compressor blew on a 102-degree Houston Saturday. Elite had a technician at our home within 90 minutes with the exact replacement capacitor and motor. Cold air restored in no time!',
        sentiment: 'positive',
        hasOwnerReply: true,
        ownerReply: 'Houston heat doesn\'t wait, and neither do we Carlos! Glad we could restore comfort for your family so quickly.',
        keywords: ['compressor', 'same-day ac repair', 'weekend dispatch'],
      },
    ],
  },
  competitors: [
    {
      id: 'comp-h1',
      name: 'Elite Climate HVAC (You)',
      isTarget: true,
      rating: 4.9,
      reviewsCount: 430,
      primaryCategory: 'HVAC Contractor',
      secondaryCategoriesCount: 2,
      photosCount: 92,
      postsPerMonth: 4,
      domainAuthority: 38,
      citationsScore: 96,
      listingAgeYears: 8,
      responseRate: 94,
      gapSummary: 'Superb customer trust and high AGR; missing Air Duct Cleaning secondary category.',
    },
    {
      id: 'comp-h2',
      name: 'Lone Star Cool & Heat',
      isTarget: false,
      rating: 4.8,
      reviewsCount: 520,
      primaryCategory: 'Air Conditioning Repair Service',
      secondaryCategoriesCount: 5,
      photosCount: 130,
      postsPerMonth: 6,
      domainAuthority: 44,
      citationsScore: 97,
      listingAgeYears: 12,
      responseRate: 88,
      gapSummary: 'Primary category set to AC repair directly gives them a slight edge on mobile voice search.',
    },
    {
      id: 'comp-h3',
      name: 'Bayou City Air Systems',
      isTarget: false,
      rating: 4.6,
      reviewsCount: 310,
      primaryCategory: 'HVAC Contractor',
      secondaryCategoriesCount: 3,
      photosCount: 65,
      postsPerMonth: 1,
      domainAuthority: 31,
      citationsScore: 85,
      listingAgeYears: 5,
      responseRate: 68,
      gapSummary: 'Slower review growth and weaker presence in West Houston.',
    },
    {
      id: 'comp-h4',
      name: 'Texas Air Masters',
      isTarget: false,
      rating: 4.7,
      reviewsCount: 460,
      primaryCategory: 'Air Conditioning Repair Service',
      secondaryCategoriesCount: 4,
      photosCount: 88,
      postsPerMonth: 3,
      domainAuthority: 39,
      citationsScore: 91,
      listingAgeYears: 10,
      responseRate: 79,
      gapSummary: 'Strong in commercial HVAC quotes, but behind in residential speed.',
    },
  ],
  actionChecklist: [
    {
      id: 'act-h1',
      title: 'Add "Air Duct Cleaning Service" Category',
      category: 'Categories',
      priority: 'High',
      effort: 'Quick Win',
      completed: false,
      description: '15,200 monthly search volume in Houston for duct cleaning & sanitization is currently uncaptured.',
      howToFix: ['Log in to GBP Manager', 'Add secondary category: Air Duct Cleaning Service'],
      expectedImpact: '+22% growth in pre-summer duct cleaning inquiries.',
    },
  ],
  recentPosts: [
    {
      id: 'post-h1',
      type: 'OFFER',
      title: '9 Comprehensive Summer AC Tune-Up',
      content: 'Prevent unexpected mid-summer breakdowns! Book our 21-point system inspection and coil wash for just 9.',
      ctaType: 'BOOK',
      ctaUrl: 'https://eliteclimatehouston.com/tuneup',
      couponCode: 'COOL59',
      dateCreated: '4 days ago',
      status: 'PUBLISHED',
    },
  ],
};

export const SAMPLE_AUDITS: Record<string, BusinessProfile> = {
  locksmith: SAMPLE_LOCKSMITH,
  dental: SAMPLE_DENTAL,
  restaurant: SAMPLE_RESTAURANT,
  hvac: SAMPLE_HVAC,
};

export function getSampleAudit(key: string): BusinessProfile {
  const normalized = key.toLowerCase().trim();
  if (normalized.includes('locksmith')) return SAMPLE_LOCKSMITH;
  if (normalized.includes('dental') || normalized.includes('dentist')) return SAMPLE_DENTAL;
  if (normalized.includes('restaurant') || normalized.includes('food') || normalized.includes('pizza') || normalized.includes('trattoria')) return SAMPLE_RESTAURANT;
  if (normalized.includes('hvac') || normalized.includes('ac') || normalized.includes('climate') || normalized.includes('heat')) return SAMPLE_HVAC;
  return SAMPLE_LOCKSMITH;
}

export function getAllSampleAudits(): BusinessProfile[] {
  return [SAMPLE_LOCKSMITH, SAMPLE_DENTAL, SAMPLE_RESTAURANT, SAMPLE_HVAC];
}

export function generateAuditFromQuery(query: string): BusinessProfile {
  const lower = query.toLowerCase();
  let base = SAMPLE_LOCKSMITH;
  if (lower.includes('dental') || lower.includes('smile') || lower.includes('teeth')) {
    base = SAMPLE_DENTAL;
  } else if (lower.includes('restaurant') || lower.includes('cafe') || lower.includes('pizza') || lower.includes('bistro') || lower.includes('diner')) {
    base = SAMPLE_RESTAURANT;
  } else if (lower.includes('hvac') || lower.includes('air') || lower.includes('cooling') || lower.includes('plumb')) {
    base = SAMPLE_HVAC;
  }

  // Create a customized instance matching query title
  const cleanTitle = query.split(',')[0].replace(/http.*$/i, '').trim() || base.name;
  return {
    ...base,
    id: 'audit-' + Math.random().toString(36).substring(2, 9),
    name: cleanTitle.length > 2 ? cleanTitle : base.name,
  };
}
